old releases compile hotfix

diff --git a/pvers b/pvers
--- a/pvers
+++ b/pvers
@@ -1,6 +1,14 @@
 #! /usr/bin/env bash
+#
+# pvers v0.6
+# PHP Version Manager
+#  
+# Ivan Zinovyev <vanyazin@gmail.com>
+#
 
 function main {
+    verbose=false
+
     # Check options
     case "$1" in
         "-h" | "--help" )
@@ -58,6 +66,25 @@ function main {
             currdir="/usr/share/pvers/current"
             confpath="/etc/php"
 
+            # Check if a wanted version is marked as an old release or not
+            oldest_version="3" # For PHP-5.3
+            wanted_version=$(echo $version | sed 's/5\.\([0-9]\{1,2\}\)\.[0-9]\{1,2\}/\1/')
+            if [[ $wanted_version -le $oldest_version ]]; then
+
+                while true; do
+                    read -p "You have selected an old version of PHP. It support is highly experimental. Really want to continue? [Y/n] " yn
+                    case $yn in
+                        [Yy]* ) break;;
+                        [Nn]* ) exit 0;;
+                        *) echo "Your answer should be directly Y or n!" ;;
+                    esac
+                done
+
+                url="http://museum.php.net/php5/"$archive
+            else
+                url="http://ru2.php.net/get/"$archive"/from/this/mirror"
+            fi
+
             # Download && Compile
             if [ ! -d $basedir ]; then
                 echo "Downloading..."
@@ -69,31 +96,25 @@ function main {
                     exit 1
                 fi
 
-                # if [[ ! -z `git --version 2>/dev/null` ]] ; then
-                    # echo "Can not run without `git`. Try to install it!"
-                    # exit 1
-                # fi
-
-                echo "http://ru2.php.net/get/"$archive"/from/this/mirror"
-                wget -q $(echo "http://ru2.php.net/get/"$archive"/from/this/mirror")
+                wget -q $url
 
                 echo "Extracting..."
 
-                mv mirror $(echo $archive)
+                if [ -f mirror ]; then
+                    mv mirror $(echo $archive)
+                elif [ ! -f $archive ]; then
+                    rm -rf $basedir
+                    echo "Failed to download! Try another version."; exit 1
+                fi
+
                 tar xjf $(echo $archive)
                 mv $(echo "php-"$version) src
-                rm $(echo $archive)
-                cd "src"
+                rm $(echo $archive)                
 
-                # Get from github
-                # git clone https://github.com/php/php-src.git
-                # cd php-src
-                # git checkout "PHP-"$version
-
-                echo "Configuring..."
-                # compile_options=("--with-openssl" "--enable-bcmath" "--enable-fpm" "--with-openssl" "--with-curl" "--enable-mbstring" "--with-mysqli" "--with-pdo-mysql" "--with-libedit" "--enable-soap" "--enable-sockets");
-                
-                compile_options=("--prefix="$builddir"\
+                echo "Configure..."
+                cd src
+                compile_options=("-q\
+                    --prefix="$builddir"\
                     --with-config-file-path="$confpath"\
                     --with-openssl\
                     --enable-bcmath\
@@ -108,10 +129,16 @@ function main {
                     --enable-sockets")
                 ./configure $compile_options
                 
-                echo "Compiling..."
-                make clean && make && make install
+                echo "Compile..."
+                if [[ `uname` == "Linux" ]]; then
+                    # Try using as much cores as possible
+                    make -s -i -k clean 1>/dev/null 2>&1 ; make -s -i -k -j $(grep -c ^processor /proc/cpuinfo) && make -s -i -k install
+                else
+                    make -s -i -k clean 1>/dev/null 2>&1 ; make -s -i -k -j && make -s -i -k install
+                fi
 
                 # Applying php.ini
+                echo "Check php.ini..."
                 if [[ ! -f /etc/php/php.ini && -f $(echo $srcdir"/php.ini-production") ]]; then
                     mkdir -p /etc/php/
                     cp -f $(echo $srcdir"/php.ini-production") /etc/php/php.ini
@@ -145,18 +172,18 @@ function help {
     "-h or --help        Print this message."\
     "-v or --version     Print pvers version."\
     "-l or --list        List locally installed PHP versions."\
-    "-d or --delete      Remove locally installed PHP version (as root only)."
+    "-d or --delete      Remove locally installed PHP version (as root only)."\
+    "-vv or --verbose    Verbose output (show all warnings and errors)."
     # -f or --force
     # -g or --global
-    # -r or --recompile all
-    # -vv or --verbose
+    # -r or --recompile all    
     printf "To install or select (if already installed) PHP of version 5.6.6 type:\n\n%s\n\n"\
     "$ pvers 5.6.6"
 }
 
 # Version
 function version {
-    printf "pvers (PHP version manager) v0.5\n"
+    printf "pvers (PHP version manager) v0.6\n"
 }
 
 # Check if user is root
@@ -167,24 +194,29 @@ function is_root {
     fi
 }
 
+# @todo Check and fix php version
+function php-version {
+    echo 'todo'
+}
+
 # @todo Check if php version exists (locally or remote)
 function exists {
-    echo $1
+    echo 'todo'
 }
 
 # @todo Select a mirror
 function mirror {
-    echo 123;
+    echo 'todo'
 }
 
 # @todo Get currently used php version
 function current {
-    echo $1
+    echo 'todo'
 }
 
 # @todo Save dir (base dir with php sources) hash after successfull install
 function save_hash {
-    echo $1
+    echo 'todo'
 }
 
 main $@
